# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171025_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='namerunner',
            new_name='name',
        ),
    ]
